name: Manual Chrome Extension Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - run: npm install
    - run: npm test

    - name: Create AeRForU ZIP
      run: |
        mkdir build
        zip -r build/AeRForU.zip data popup images scripts manifest.json README.md

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: AeRForU Build ${{ github.run_number }}
        files: build/AeRForU.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
